create table cursos (
    id integer generated by default as identity,
    descricao varchar(500) ,
    nome varchar(100) not null,
    primary key (id)
);

insert into cursos (descricao, nome) values ('Curso de Java', 'Java'),('Curso de DSM', 'DSM'),('Curso de Administração','ADM');
